version: "3.7"
services:
  service:
    build: .
    restart: no
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/facultydb?useSSL=false&allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb
    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.2.0"
    restart: no
    ports:
      - 3306:3306
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: facultydb
      MYSQL_ROOT_PASSWORD: 12345678QB
      MYSQL_USER: someuser
      MYSQL_PASSWORD: somepassword
networks:
  springapimysql-net: